baseURL = "/"
languageCode = "en-us"
title = "Nicholi.io"
summaryLength = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.nav]]
    identifier = "about-me"
    name = "About Me"
    url = "/"
    weight = 1
  [[menu.nav]]
    identifier = "traditional-media"
    name = "Traditional Media"
    url = "/traditional-media/"
    weight = 2
  [[menu.nav]]
    identifier = "virtual-reality"
    name = "Virtual Reality"
    url = "/virtual-reality/"
    weight = 3
  [[menu.nav]]
    identifier = "blog"
    name = "Blog"
    url = "https://bravemetaverse.com/blog/"
    weight = 4